# Generated by Django 3.2.3 on 2021-05-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwd',
            new_name='password',
        ),
    ]
