# Generated by Django 3.2.3 on 2021-05-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Network', models.CharField(max_length=255)),
                ('Release_Date', models.DateField()),
            ],
        ),
    ]
