# Generated by Django 3.2.3 on 2021-05-25 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='Des',
            field=models.TextField(default='nice show'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shows',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-05-25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shows',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
